import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        publishableKey="pk_live_Y2xlcmsudGF1cmkubG9jYWxob3N0JA"
        appearance={{
          baseTheme: undefined,
          layout: {
            socialButtonsPlacement: "bottom",
            socialButtonsVariant: "blockButton",
          },
        }}
      >
        <Providers>
          <body className={inter.className}>
            {children}
            <Toaster />
          </body>
        </Providers>
      </ClerkProvider>
    </html>
  );
}
