pub mod core;
mod utils;
pub mod vad;
pub use transcription::stt::stt;
pub use transcription::{AudioInput, TranscriptionResult};
pub mod speaker;
pub mod transcription;
pub use utils::audio::pcm_decode;
pub use utils::audio::resample;
pub mod audio_manager;
mod device;
mod segmentation;
