pub mod core;
mod utils;
pub mod vad;
pub use transcription::stt::{create_whisper_channel, stt};
pub use transcription::{AudioInput, TranscriptionResult};
pub mod speaker;
pub mod transcription;
pub use utils::audio::pcm_decode;
pub use utils::audio::resample;
pub mod audio_manager;
mod device_manager;
mod segmentation_manager;
