import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HealthStatus from "@/components/screenpipe-status";
import { PHProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PHProvider>
        {/* https://posthog.com/docs/libraries/next-js for more info */}
        <body className={inter.className}>{children}</body>
      </PHProvider>
    </html>
  );
}
