name: Generate CHANGELOG.md

on: [workflow_call]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Generate Changelog
        run: .github/scripts/generate_changelog_md.sh

      - name: Commit and push changelog files
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout -b feat/changelog-${{ env.CURRENT_RELEASE }}
          git add content/changelogs/$CURRENT_RELEASE.md content/changelogs/CHANGELOG.md screenpipe-app-tauri/public/CHANGELOG.md
          git commit -m "docs: add changelog for ${{ env.CURRENT_RELEASE }}"
          git rebase origin main
          git push -u origin feat/changelog-${{ env.CURRENT_RELEASE }}
      
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr create --base main --head feat/changelog-${{ env.CURRENT_RELEASE }} --title "docs: add changelog for ${{ env.CURRENT_RELEASE }}" --body "Automated PR to add the changelog for ${{ env.CURRENT_RELEASE }}"
